### PR TITLE
Kelsey's repository

### PR DESCRIPTION
**Pull request by kelsey-huisman**
here it is!

### CODE REVIEW

**Comment by crsl4** [comment]
I still see merging conflicts, Kelsey!

**Comment by kelsey-huisman** [comment]
yes, i'm not sure why i'm having such a hard time with it. i'm going to try again later.

**Comment by crsl4** [comment]
no worries! I think that we should do it step by step with you sharing your screen next time

**Comment by crsl4** [comment]
yay! it works now!

**Pull request merged**
